version: '3'
services:
  front-release2:
    image: nexusdocker.luxfacta.com/luxfacta/projetos/aceite/sgm/release200/sbei-sk-sgm-front
    networks:
      - traefik_net
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.frontend.rule=Host:sgm.luxfacta.com"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_net"
      - "traefik.backend=sgmreleasefront"
      - "traefik.frontend.entryPoints=http,https"
networks:
 traefik_net:
  external:
   name: traefik_net